import { createTypes } from 'reduxsauce';

export default createTypes(`
  STARTUP

  OAUTH_STATE_CHANGE

  MENU_VISIBLE_CHANGE
  MENU_SHOW_FILES_CHANGE
  MENU_SELECT_FILE_CHANGE
  MENU_CURRENT_DIR_CHANGE

  MODAL_VISIBLE_CHANGE

  EDIT_OPENED_FILE_CHANGE
  EDIT_OUTPUT_DIFF_CHANGE
  EDIT_OUTPUT_COMMENTS_CHANGE
`);
